# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTQ5YWI4OTAwNmY3NGM3OTkyYTk2ZDIxYWQ1YzcxYTE2ZDZhZjgwODBhMDdiODg2MzQ5MjBjZjdmNmYyZDBkZTJmZWUyNTIzMzI1MmIwNWFjMDY5YjI1MzUzMDI3OTMzNWVkMmU2NjIzMzUzMmVlYTU0ZWZiN2Y4NGFhZmM5OWI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
